### PR TITLE
Add contract + tests using storage

### PR DESCRIPTION
**Pull request by gRoussac**
- Main contract can be found /contract/src/main.rs, it mainly uses put_key and storage::write

- Additional client contract can be found in /client/named_key_session, it mainly uses get_key and storage::read

- Tests are in tests/src/integration_tests.rs and are divided in 2 parts
    - Testing installation and named keys in account's context
    - Testing getting named keys and storage read with a session call 

Any question, typo, required change please let me know

### CODE REVIEW

**Comment by gRoussac** [comment]
This PR will be squashed into dev branch, then pushed to main when done.

**Comment by ipopescu** [comment]
Adding @ACStoneCL who will work on the docs.

**Comment by gRoussac** [comment]
@darthsiroftardis @ipopescu @ACStoneCL closing this PR in favor of new repo + deleting that empty repo

**Comment by gRoussac** [comment]
@darthsiroftardis @ipopescu @ACStoneCL closing this PR in favor of new repo + deleting that empty repo

**Pull request closed without merging**
